#!/usr/bin/env bash
set -euo pipefail

echo "Collecting garbage older than 7 days..."
nix-collect-garbage --delete-older-than 7d
sudo nix-collect-garbage --delete-older-than 7d
echo "Garbage collection complete."
