{ config, pkgs, user, ... }:
let
  hostname = config.networking.hostName;
  release = config.system.nixos.release;
  stateVersion = config.system.stateVersion;

  # Local NixOS modules imported for this host (hardcoded — one host, known imports)
  enabledModules = builtins.concatStringsSep "\n" [
    "- modules/nixos/core.nix"
    "- modules/nixos/audio.nix"
    "- modules/nixos/nvidia.nix"
    "- modules/nixos/hyprland.nix"
    "- modules/nixos/cua.nix"
    "- modules/nixos/power.nix"
    "- modules/nixos/stylix.nix"
    "- modules/nixos/greetd.nix"
    "- modules/nixos/agent-context.nix"
  ];
in
{
  system.activationScripts.agentContext.text = ''
    _agent_context_generate() {
      local kernel gpu timestamp
      kernel="$(${pkgs.coreutils}/bin/uname -r)"
      gpu="$(${pkgs.pciutils}/bin/lspci 2>/dev/null | ${pkgs.gnugrep}/bin/grep -i vga || echo "unknown")"
      timestamp="$(${pkgs.coreutils}/bin/date -Iseconds)"

      ${pkgs.coreutils}/bin/cat > /etc/agent-context.md.tmp << CTXEOF
    # System Context — ${hostname}
    Generated: $timestamp

    ## System
    - NixOS ${release}, x86_64-linux, kernel $kernel
    - Flake: ~/nix-config#${hostname}
    - GPU: $gpu

    ## Configuration Paths
    - Flake entry point: flake.nix
    - Host config: hosts/${hostname}/default.nix
    - System packages: modules/nixos/core.nix (environment.systemPackages)
    - User packages: home/common/dev-tools.nix (home.packages)
    - Shell/aliases: home/common/shell.nix
    - Desktop/Hyprland: home/linux/hyprland.nix
    - Theming: modules/nixos/stylix.nix

    ## Enabled Modules
    ${enabledModules}

    ## System Packages (core.nix)
    curl, file, git, htop, sbctl, unzip, wget

    ## User Packages (dev-tools.nix)
    bat, claude-code, codex, eza, fd, fzf, gemini-cli, gh, jq, lazygit, nodejs, opencode, python3, ripgrep, rustup

    ## AI Agent Status (live, queryable)
    - A user daemon (home/linux/agent-status.nix) reports which AI coding agents are
      running (claude, codex, gemini, opencode), each running agent's latest
      user/assistant message, and every parallel session (per working directory). It
      rescans every 1s.
    - It publishes \$XDG_RUNTIME_DIR/agent-status.json. Query it with the
      "agent-status" command (also: agent-status --json, agent-status <name>), or read
      the JSON directly with jq. The cycle-through list is .hyprlock.sessions.
    - Consumers: the Hyprland lock screen (home/linux/hyprlock.nix JRPG widget) and the
      waybar agent indicator (home/linux/waybar.nix custom/agent) both read this file —
      anything else can too. The lock-screen box auto-hides when nothing runs; with
      multiple sessions, Super+] / Super+[ cycle through them. Each harness has its own
      animated pixel mascot (Clawd for claude, plus teal/sparkle/amber sprites for
      codex/gemini/opencode); the avatar shows the current session's agent and swaps as
      you cycle (sprites in assets/mascots/, generated by home/linux/mascot-gen.sh).
    - Service: systemctl --user status agent-status. Schema + how to add an agent:
      docs/agent-status.md

    ## AI Agent Spawn (launch new agent sessions)
    - The "agent-spawn" command (home/linux/agent-status.nix) launches a NEW agent
      session in its own detached tmux session, with CLI flags baked into named
      presets so you never look up per-harness bypass flags:
        agent-spawn --list                  show presets
        agent-spawn <preset> [dir] [prompt]  spawn; prints the tmux session name
      Presets: claude, codex, opencode (bypass-permissions ON) plus claude-safe,
      codex-safe, opencode-safe (no bypass). dir and prompt are positional (2nd and
      3rd): dir defaults to the cwd, prompt is optional, but to seed a prompt in the
      current dir pass dir explicitly: agent-spawn claude . "fix the build".
    - Fire-and-forget: it returns immediately and prints the session name. Attach or
      pilot it over plain tmux — tmux attach -t <name>, tmux send-keys -t <name> ...,
      tmux capture-pane -t <name> -p. Spawned sessions auto-appear in agent-status
      (and waybar / the lock screen). A claude session can drive a codex/opencode
      session this way (they lack native remote control).
    - Reference: docs/agent-status.md

    ## AI Computer-Use (CUA) — see & act on the desktop (harness-agnostic)
    - The "cua" command lets ANY agent see and act on the Wayland desktop. A user
      daemon (home/linux/cua.nix) brokers Hyprland's single seat as a serialized
      lease and publishes \$XDG_RUNTIME_DIR/cua-status.json. Shell out to it:
        cua see [TARGET]                 screenshot a target (PNG path; no lease)
        cua target new --headless        spawn an off-screen sandbox output
        cua acquire <TARGET>             take the seat (sandbox = self-serve)
        cua click/type/scroll/key ...    act (must hold the lease)
        cua release ; cua status
    - TARGET is "real" (the user's desktop) or a "sandbox-N" id from "target new".
    - The REAL desktop is push-to-grant: an agent canNOT drive it until the USER
      runs "cua grant <agent> real" (optionally --lock). Panic key Super+Shift+Esc
      (or "cua panic") instantly returns the seat. Sandboxes need no grant.
    - Reference + full verb list + safety model + R-IDs: docs/cua.md
    - Services: systemctl --user status cua ydotoold

    ## Constraints
    - Do NOT edit hardware-configuration.nix manually
    - Do NOT change system.stateVersion or home.stateVersion (currently ${stateVersion})
    - Do NOT hardcode usernames — use the user variable (currently "${user}")
    - Do NOT add NixOS-specific options in home/common/ (use home/linux/)
    - Lanzaboote: 10 bootloader generation limit — run bash apps/clean between major rebuild batches
    - Auto-upgrade: 04:00 from github:jvall0228/nix-config/main — commit and push before expecting persistence
    CTXEOF

      ${pkgs.coreutils}/bin/chmod 0644 /etc/agent-context.md.tmp
      ${pkgs.coreutils}/bin/mv /etc/agent-context.md.tmp /etc/agent-context.md
    }

    if ! _agent_context_generate; then
      echo "WARNING: agent-context generation failed" | ${pkgs.systemd}/bin/systemd-cat -t agent-context -p warning
    fi
  '';
}
